name: ai-pr-guard
description: PR safety report for AI-generated code (solo makers)
author: <your name or org>

branding:
  icon: shield
  color: blue

inputs:
  github_token:
    description: GitHub token (use secrets.GITHUB_TOKEN)
    required: true

outputs:
  comment_body:
    description: Markdown PR safety report

runs:
  using: node24
  main: dist/index.js
